### ISSUE TITLE
media-gfx/makehuman-1.1.0-r3 fails to fetch

### ISSUE THREAD

**Issue by turion** [brothermechanic/cg#10]
`>>> Downloading 'ftp://ftp.lecl.net/pub/gentoo/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz'
--2016-06-03 23:20:47--  ftp://ftp.lecl.net/pub/gentoo/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz
           => ‘/usr/portage/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz’
Resolving ftp.lecl.net... 2001:470:23:3e::2, 112.169.81.98
Connecting to ftp.lecl.net|2001:470:23:3e::2|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/gentoo/distfiles ... done.
==> SIZE makehuman_1.1.0~rc3+20160416132607.orig.tar.gz ... done.

==> EPSV ... done.    ==> RETR makehuman_1.1.0~rc3+20160416132607.orig.tar.gz ... 
No such file ‘makehuman_1.1.0~rc3+20160416132607.orig.tar.gz’.

> > > Downloading 'http://mirror.qubenet.net/mirror/gentoo/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz'
> > > --2016-06-03 23:20:53--  http://mirror.qubenet.net/mirror/gentoo/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz
> > > Resolving mirror.qubenet.net... 2a01:90:0:7::10, 81.91.242.10
> > > Connecting to mirror.qubenet.net|2a01:90:0:7::10|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2016-06-03 23:20:53 ERROR 404: Not Found.
> > > 
> > > Downloading 'ftp://91.121.124.139/gentoo-distfiles/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz'
> > > --2016-06-03 23:20:53--  ftp://91.121.124.139/gentoo-distfiles/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz
> > >            => ‘/usr/portage/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz’
> > > Connecting to 91.121.124.139:21... connected.
> > > Logging in as anonymous ... Logged in!
> > > ==> SYST ... done.    ==> PWD ... done.
> > > ==> TYPE I ... done.  ==> CWD (1) /gentoo-distfiles/distfiles ... 
> > > No such directory ‘gentoo-distfiles/distfiles’.
> > > 
> > > Downloading 'http://mirror.netcologne.de/gentoo/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz'
> > > --2016-06-03 23:20:54--  http://mirror.netcologne.de/gentoo/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz
> > > Resolving mirror.netcologne.de... 2001:4dd0:1234:1::deb, 194.8.197.22
> > > Connecting to mirror.netcologne.de|2001:4dd0:1234:1::deb|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2016-06-03 23:20:54 ERROR 404: Not Found.
> > > 
> > > Downloading 'ftp://ftp.df.lth.se/pub/gentoo/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz'
> > > --2016-06-03 23:20:54--  ftp://ftp.df.lth.se/pub/gentoo/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz
> > >            => ‘/usr/portage/distfiles/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz’
> > > Resolving ftp.df.lth.se... failed: Name or service not known.
> > > wget: unable to resolve host address ‘ftp.df.lth.se’
> > > Downloading 'http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu/pool/main/m/makehuman/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz'
> > > --2016-06-03 23:20:54--  http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu/pool/main/m/makehuman/makehuman_1.1.0~rc3+20160416132607.orig.tar.gz
> > > Resolving ppa.launchpad.net... 91.189.95.83
> > > Connecting to ppa.launchpad.net|91.189.95.83|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2016-06-03 23:20:54 ERROR 404: Not Found.

!!! Couldn't download 'makehuman_1.1.0~rc3+20160416132607.orig.tar.gz'. Aborting.`

**Comment by brothermechanic** [comment]
updated http://wstaw.org/m/2016/06/04/plasma-desktopJC4176.png

**Comment by turion** [comment]
Thanks, fixed for me!
