### ISSUE TITLE
VERIFY FAILED: media-libs/opencolorio-1.0.9-r4::cg

### ISSUE THREAD

**Issue by ganthore** [brothermechanic/cg#17]
media-libs/opencolorio-1.0.9-r4::cg from recent update fails to install with the following error:

!!! Fetched file: opencolorio-1.0.9-git.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      13744837
!!! Expected: 13740765
Refetching... File renamed to '/usr/portage/distfiles/opencolorio-1.0.9-git.tar.gz._checksum_failure_.mdwno6jy'

**Comment by brothermechanic** [comment]
it works fine in my case
please try agane

**Comment by o01eg** [comment]
I also got that error with the same filesizes. Could you check if opencolorio archive was changed?

**Comment by Alamot** [comment]
I get that error too.

**Comment by brothermechanic** [comment]
fixed!
sorry for delay
