### ISSUE TITLE
Mission deps on media-video/shotcut ebuild

### ISSUE THREAD

**Issue by Clind99** [brothermechanic/cg#22]
Hello, I don't know if you are the person maintaining this ebuild (if there is such a person) but there's a fews deps missing to shotcut in the ebuild I gat from your overlay. Following is the list of these deps with details. If you're not this person sorry for the bother, and can you tell me wherer I should post this ?

dev-qt/qtwebsockets
dev-qt/qtgraphicaleffects
media-plugins/vidstab (deshake to enable video filter)
media-libs/mlt melt qt5 frei0r (melt use and un /usr/bin/, ln -s melt qmelt, use and linking required in order to have video export working)

Thanks for the overlay and the ebuild :)
Clind

**Comment by brothermechanic** [comment]
Hello
I'm losr priority to hold this ebuild, because this software isn't pro tool. Blender still better for montage.
I will plan to delete it.
If you want, you can modify this ebuild.
