### ISSUE TITLE
MakeHuman 1.1.1 available & MakeHuman 1.1.0-r4 SRC_URI broken

### ISSUE THREAD

**Issue by crocket** [brothermechanic/cg#27]
I request that MakeHuman 1.1.1 be available on this overlay.

`media-gfx/makehuman-1.1.0-r4` couldn't be installed because SRC_URI is broken.

**Comment by Sur3** [comment]
I second this, @brothermechanic may I ask why was makehuman removed and this bug closed without a version bump?

**Comment by crocket** [comment]
Perhaps, he uses a better alternative to makehuman or doesn't use it anymore.

**Comment by brothermechanic** [comment]
Please, look at ManuelbastioniLAB

**Comment by crocket** [comment]
Oh, an addon to turn blender into a 3D humanoid creator.

**Comment by brothermechanic** [comment]
added makehuman ebuild!

**Comment by crocket** [comment]
Thanks

**Comment by brothermechanic** [comment]
update,
stuppid ubuntu sources was with bug
now all from thunk
