### ISSUE TITLE
Why the revisions on -9999 ebuilds ?

### ISSUE THREAD

**Issue by nado** [brothermechanic/cg#29]
For example : dev-games/godot-9999-r1

This does not make much sense and forces priority of your ebuilds over other overlays with higher priority in repos.conf

Do you have a strong reason to use it ? Would you revert it ? Otherwise, the only way I see how to use your overlay is by masking everything by default and unmasking the ebuilds I want from yours (for the moment, only makehuman), which makes it less practical.

**Comment by nado** [comment]
Also a -9999 ebuild should not be keyworded.

**Comment by brothermechanic** [comment]
i will fix it)
