### ISSUE TITLE
unreal-engine build error

### ISSUE THREAD

**Issue by mistafunk** [brothermechanic/cg#34]
--2019-05-22 11:53:28--  http://104.19.138.75/gentoo/distfiles/UnrealEngine-4.22.1-release.tar.gz
Connecting to 104.19.138.75:80... connected.
HTTP request sent, awaiting response... 403 Forbidden

thanks!

**Comment by brothermechanic** [comment]
you need download it manually

**Comment by brothermechanic** [comment]
this is wip for now
i cant to finish developing this ebuild, very hard for me)

**Comment by mistafunk** [comment]
i see, thanks
