### ISSUE TITLE
Linuxcnc ebuild

### ISSUE THREAD

**Issue by Petross404** [brothermechanic/cg#36]
Hello there. I see that you are serious about coomputer graphics programs on Gentoo. Do you know linuxcnc and could you try to write an ebuild?

Thank you.

**Comment by brothermechanic** [comment]
Hello
In cg overlay I hold only software used (and tested) by me
I don't linuxcnc, and dont heared about
I can try to port it if you will support me 
Can you?

**Comment by Petross404** [comment]
> Hello
> In cg overlay I hold only software used (and tested) by me
> I don't linuxcnc, and dont heared about
> I can try to port it if you will support me
> Can you?

Well I can try. I have some old ebuilds for it but something doesn't work. Let me find them and post them here to discuss them.

**Comment by brothermechanic** [comment]
you can create yours own repo and post link here

**Comment by Petross404** [comment]
https://github.com/Petross404/testing/tree/master/sci-electronics/linuxcnc

Here it is. For me it fails about Boost::Python.
