### ISSUE TITLE
Bad checksum on FreeCAD binary

### ISSUE THREAD

**Issue by goverp** [brothermechanic/cg#43]
The checksums on your media-gfx/freecad-bin ebuild seem to be out of date.  The FreeCAD git repository currently has only an SHA256 checksum, and neither the BLAKE2B nor the SHA512 values in the ebuild match.

For anyone else hitting this, you can rename the ._checksum_failure_. file without the suffix, and edit the ebuild Manifest file to contain the SHA256 value direct from the FreeCAD Github repository at:
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD_0.18-16146-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage-SHA256.txt

**Comment by brothermechanic** [comment]
please, use source based version
