### ISSUE TITLE
lightworks build no ebuilds to satisfy "media-libs/jpeg:8"

### ISSUE THREAD

**Issue by HougeLangley** [brothermechanic/cg#44]
$ sudo emerge -av media-video/lightworks 

 * IMPORTANT: 12 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "media-libs/jpeg:8".
(dependency required by "media-video/lightworks-14.5-r12::cg" [ebuild])
(dependency required by "media-video/lightworks" [argument])

**Comment by HougeLangley** [comment]
![2020-08-28_02-40](https://user-images.githubusercontent.com/1161594/91481976-dfe28b00-e8d7-11ea-881f-ab7ec541a843.png)

**Comment by brothermechanic** [comment]
Updated
