### ISSUE TITLE
blender-2.90.0.ebuild

### ISSUE THREAD

**Issue by brothermechanic** [brothermechanic/cg#50]
@anex5
did you try to build blender-2.90.0.ebuild?
I build it for my needs and found that media-blender/addons media-blender/addons_contrib dont connected with
May be delete blender-2.90.0.ebuild file?

**Comment by anex5** [comment]
Do you mean media-blender/addons media-blender/addons_contrib installs into different directory (/usr/share/blender/2.91/scripts/addons) due to different slot number?
I would leave blender-2.90.0.ebuild for test purposes.

**Comment by brothermechanic** [comment]
oh, exactly
I was sleepy)
i will add a fix later)))
