### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [brothermechanic/cg#52]
Hi!

Thank you for this Gentoo overlay!

Could you please add `LICENSE` file, describing is it allowed to copy, change and use this repository in any purpose?
It would be great to see any popular open source license.

**Comment by brothermechanic** [comment]
Thank you!)
I will do that, 
but anyway - this is opensource and almost every ebuild has this lines
 Copyright 1999-2019 Gentoo Foundation
 Distributed under the terms of the GNU General Public License v2
so you feel free to use and change it

**Comment by brothermechanic** [comment]
And, you can support me by paypal, if you want)

**Comment by vazhnov** [comment]
@brothermechanic , is it possible to create `LICENSE` file in the root of git repository or at least add license information into `README.md`?

**Comment by brothermechanic** [comment]
done!)
