### ISSUE TITLE
Fix mirroring please

### ISSUE THREAD

**Issue by FlyingWaffleDev** [brothermechanic/cg#57]
All ebuilds in this overlay are left without the 'mirror' or 'primaryuri' restrict keywords.  This means that every time one of your ebuilds is run it checks through the Gentoo mirrorlist for the ebuild package files, which do not exist since only the main Gentoo tree is mirrored!

Please add 'RESTRICT="primaryuri"' to your ebuilds at the very least, so users aren't stuck waiting hours for mirror downloads to finally time out and just fetch from the primary uri.  This is especially annoying when waiting for the 10+ affected packages that are required by Blender.

**Comment by tychota** [comment]
+1 on this

Gentoo docs says it shouldn't be used ?

![image](https://user-images.githubusercontent.com/13785185/119511663-ee7ca680-bd72-11eb-951d-abefa2ff7790.png)

@FlyingWaffleDev is the above text only for gentoo own tree ?

---

I can help on this. What I'm I supposed to do ?
- clone
- add RESTRICT
- run ebuild manifest
- make a PR 

?
