### ISSUE TITLE
dev-cpp/pystring don't support gcc-10*

### ISSUE THREAD

**Issue by brothermechanic** [brothermechanic/cg#58]
http://dpaste.com/5CCL3ENUA
@anex5 , can you check it in free time?

**Comment by anex5** [comment]
Похоже нехватает libc. Поправил BDEPEND. У меня собирается без ошибок, так что проверить не могу.
PS в [логе](https://dpaste.com/5CCL3ENUA) версия gcc `9.3.0`. Может не тот компилятор выбран?

**Comment by brothermechanic** [comment]
компилятор один, новая система
странно
а у тебя 10й gcc?

**Comment by anex5** [comment]
Да. У меня gcc 10.2.0-r3

**Comment by brothermechanic** [comment]
попробовал тупо
```
# cd /usr/lib/gcc/x86_64-pc-linux-gnu/
# ln -s 10.2.0 9.3.0
```
но
`/usr/bin/install: cannot remove '/usr/include/pystring/pystring.h': Permission denied`
http://dpaste.com/HSHUF9U4R

**Comment by anex5** [comment]
emerge или ebuild запускался с правами root?
`ls -al /usr/include/pystring/`?

**Comment by brothermechanic** [comment]
конечно, а как иначе?
```
$ ls -al /usr/include/pystring/
итого 68
drwxr-xr-x   2 root root  4096 мар 20 18:17 .
drwxr-xr-x 384 root root 36864 апр  7 15:20 ..
-rw-r--r--   1 root root 23403 мар 20 18:17 pystring.h
```

**Comment by brothermechanic** [comment]
можешь компетентно ответить сюда?
https://github.com/imageworks/pystring/issues/28

**Comment by anex5** [comment]
http://dpaste.com/5CCL3ENUA больше не доступен.
Обновил ebuild. Попробуй удалить pystring и установить заново.
Возможно набор FEATURES в make.conf не позволяeт заменять файл pystring.h

**Comment by brothermechanic** [comment]
та же петрушка http://dpaste.com/CRKCU44LU

**Comment by brothermechanic** [comment]
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"

**Comment by anex5** [comment]
Насколько я помню в прошлый раз проблема заключалась в `Permission denied`, а сейчас `gcc 9.3.0`.
Заметил, что применяется userpatch из /etc/portage/patches
`* Applying makefile.patch ...`
Попробуй убрать его. 
Если возникнет проблема с разрешениями попробуй закоментировать сторочку c doheader в ebuild и покажи лог.

**Comment by brothermechanic** [comment]
емае))) сам себе злобный буратино, а я забыл что там был патч, убрал и с симлинком на 9,3,0 все хорошо собирается, а  без него нет http://dpaste.com/BF95Y6HHA, ну и ладно, жить можно)
спасибо за помощь.

**Comment by brothermechanic** [comment]
подсказали в апстриме!
https://github.com/imageworks/pystring/issues/28?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE3MzQwNTYzOTg6MzEwOTk5NQ%3D%3D#issuecomment-822626435
