### ISSUE TITLE
can't find file to patch at input line 4

### ISSUE THREAD

**Issue by andreassen51** [brothermechanic/cg#60]
I would like to build blender-2.92.0 but the patch failed on my stable system. blender-2.93.0 built but it's not as stable to run.

 * Applying x112.patch ...
patching file intern/ghost/CMakeLists.txt
Hunk #1 succeeded at 192 with fuzz 1 (offset 9 lines).
Hunk #2 succeeded at 253 with fuzz 2 (offset 12 lines).
Hunk #3 succeeded at 266 with fuzz 2 (offset 15 lines).
Hunk #4 succeeded at 283 with fuzz 2 (offset 18 lines).                                    [ ok ]
 * Applying blender-system-glog-gflags.patch ...                                           [ ok ]
 * Applying cg-addons.patch ...                                                            [ ok ]
 * Applying cg-defaults.patch ...                                                          [ ok ]
 * Applying cg-keymap.patch ...
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -Naur a/release/scripts/presets/keyconfig/blender.py b/release/scripts/presets/keyconfig/blender.py
|--- a/release/scripts/presets/keyconfig/Blender.py	2020-12-24 20:07:32.000000000 +0300
|+++ b/release/scripts/presets/keyconfig/Blender.py	2020-12-27 20:56:46.597343465 +0300
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
patching file release/scripts/presets/keyconfig/keymap_data/blender_default.py
Hunk #3 succeeded at 409 (offset 5 lines).
Hunk #4 succeeded at 518 (offset 5 lines).
Hunk #5 succeeded at 937 (offset 13 lines).
Hunk #6 succeeded at 2015 (offset 61 lines).
Hunk #7 succeeded at 4062 (offset 84 lines).
Hunk #8 succeeded at 4117 (offset 83 lines).
Hunk #9 succeeded at 4143 (offset 83 lines).
Hunk #10 succeeded at 4676 (offset 84 lines).                                              [ !! ]
 * ERROR: media-gfx/blender-2.92.0::cg failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/media-gfx/blender-2.92.0/files/cg-keymap.patch
 *

**Comment by brothermechanic** [comment]
Hello
I'm allways support only latest builds, 2.92 wil be removed soon.
You can copy 2.92 ebuild to your local overlay and comment cg-keymap.patch in it.

What problem do you have with 2.93? (It's much faster for me than 2.92)

**Comment by andreassen51** [comment]
Hi, I was having problems with the 2.92 demo file and I was already able to build 2.93, so the newer version shouldn't have been the problem. Booted up the Ubuntu and loaded up 2.93 with the snap version there and the program dies there in exactly the same way (the terminal says "killed").

It took me three hours with Ubuntu to discover I shouldn't use the "GPU Compute" for that demo. The program halts without any ceremony what so ever.

I thought my GPU was about to die and in the other distro I had no other demo downloaded. I'm rocking a i7 8700, unchecked 64Gb and the Asus 2070 8Gb. With one setting it also said my GPU is out of resources - adding just 1600 Mb on my 8 Gb card.

So I'm back because I'm trying to learn some of the new things, I haven't touched blender since 2.78 with a Linux Format tutorial.

I have used Gentoo since 2007. Thanks for all your work, I have only added the cg repository from there, to emerge 2.93.0 I had to deal with the Python horseplay, some dependencies need python3_9 flags. The files with the useflags were already in my /root folder (lol dated 2016), some version numbers had to change and that was basically it.

Although the blender page says 2.92.0 I'll work with 2.93.0 for now.

Thanks.

**Comment by andreassen51** [comment]
I've solved the memory problem, it was an easy one.

Your recommendation worked well, thanks. I'm not found of local repos and I have a few patches in etc/portage (opensubdiv, xfce-sensors..), I'll hope my local repo could be removed without chroot-ing.

My machine has 64Gb and I was overzealous to run without the swap partitions. I have two of the partitions on some spinning rust and when I've mounted both 4Gb swap partitions, 'top' shows me that 6.5 Gb is consumed during the render of the 2.92 picture (the dinosaur with pups). This blender is a demanding one and had thrown me a red herring bug if I've ever seen one.

I'm also mounting a 14Gb memory temp file to save my nvme drive. It's always good to check I've turned it off before starting blender, X-Plane, darktable..

Regards.

**Comment by brothermechanic** [comment]
Yes, the blender loves memory. Especially if you have many polygons in the scene.
I also have 64, but it happens not enough with a comprehensive scene, for example, a detailed big city.
I also add with a swap file, it is useful compared to the swap partition. 
Sorry for big delay...
