### ISSUE TITLE
Some ebuilds need updating EAPI

### ISSUE THREAD

**Issue by lisyarus** [brothermechanic/cg#61]
This happens at repository syncing stage (via `eix-sync`): egencache fails due to some ebuilds using too old EAPI versions which are no longer supported by some of the called eclasses. In particular,

* `dev-util/nvidia-cuda-sdk` fails with `Unsupported EAPI=6 (too old) for cuda` due to `cuda.eclass` explicitly requiring EAPI=7 or 8 (here's the [gentoo repo commit](https://github.com/gentoo/gentoo/commit/e9bb2213bb895e4a26c3e2a5a972c255d0d0af24) that updates `dev-util/nvidia-cuda-sdk` to EAPI=7)
* `media-makehuman/mhx2-makehuman-exchange` fails similarly due to `mercurial.eclass` supporting EAPI=7 exclusively
* `x11-misc/xbindkeys-config` fails with `eutils: EAPI 4 not supported` due to `eutils.eclass` explicitly requiring at least EAPI=5
* `media-plugins/refocus-it` lacks a EAPI specification (which is supposedly defaulted to 0 in this case) and fails with `eutils: EAPI 0 not supported`

**Comment by tanuki-no** [comment]
Got the same issue:

[1] «cg» /var/db/repos/cg (кэш: parse|ebuild*#metadata-md5#metadata-flat#assign)
     Чтение категории  60|173 ( 34): dev-util… * ERROR: dev-util/nvidia-cuda-sdk-10.1.105::cg failed (depend phase):
 *   Unsupported EAPI=6 (too old) for cuda
 * 
 * Call stack:
 *                         ebuild.sh, line 645:  Called source '/var/db/repos/cg/dev-util/nvidia-cuda-sdk/nvidia-cuda-sdk-10.1.105.ebuild'
 *   nvidia-cuda-sdk-10.1.105.ebuild, line   6:  Called inherit 'cuda' 'flag-o-matic' 'portability' 'toolchain-funcs' 'unpacker' 'versionator'
 *                         ebuild.sh, line 329:  Called __qa_source '/usr/portage/eclass/cuda.eclass'
 *                         ebuild.sh, line 114:  Called source '/usr/portage/eclass/cuda.eclass'
 *                       cuda.eclass, line   6:  Called die
 * The specific snippet of code:
 *   		die "Unsupported EAPI=${EAPI:-0} (too old) for ${ECLASS}"
 * 
 * If you need support, post the output of `emerge --info '=dev-util/nvidia-cuda-sdk-10.1.105::cg'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/nvidia-cuda-sdk-10.1.105::cg'`.
 * Working directory: '/usr/lib/python3.9/site-packages'
 * S: '/nvidia-cuda-sdk-10.1.105'

Ошибка ебилда с состоянием 1
     Чтение категории  60|173 ( 34): dev-util…
Не получилось исполнить /var/db/repos/cg/dev-util/nvidia-cuda-sdk/nvidia-cuda-sdk-10.1.105.ebuild
     Чтение категории  60|173 ( 34): dev-util… * ERROR: dev-util/nvidia-cuda-sdk-10.1.168::cg failed (depend phase):
 *   Unsupported EAPI=6 (too old) for cuda
 * 
 * Call stack:
 *                         ebuild.sh, line 645:  Called source '/var/db/repos/cg/dev-util/nvidia-cuda-sdk/nvidia-cuda-sdk-10.1.168.ebuild'
 *   nvidia-cuda-sdk-10.1.168.ebuild, line   6:  Called inherit 'cuda' 'flag-o-matic' 'portability' 'toolchain-funcs' 'unpacker' 'versionator'
 *                         ebuild.sh, line 329:  Called __qa_source '/usr/portage/eclass/cuda.eclass'
 *                         ebuild.sh, line 114:  Called source '/usr/portage/eclass/cuda.eclass'
 *                       cuda.eclass, line   6:  Called die
 * The specific snippet of code:
 *   		die "Unsupported EAPI=${EAPI:-0} (too old) for ${ECLASS}"
 * 
 * If you need support, post the output of `emerge --info '=dev-util/nvidia-cuda-sdk-10.1.168::cg'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/nvidia-cuda-sdk-10.1.168::cg'`.
 * Working directory: '/usr/lib/python3.9/site-packages'
 * S: '/nvidia-cuda-sdk-10.1.168'

Ошибка ебилда с состоянием 1
     Чтение категории  60|173 ( 34): dev-util…
Не получилось исполнить /var/db/repos/cg/dev-util/nvidia-cuda-sdk/nvidia-cuda-sdk-10.1.168.ebuild
     Чтение категории 173|173 (100) Готово
